# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  
steps:

- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: '$(Build.SourcesDirectory)'
    FodConnection: 'fod'
    ReleaseOptions: '0'
    ReleaseId: 143395
    EntitlementSelection: '1'
    EntitlementPreference: '3'
    OverrideScanSettings: '2'
    InProgressScanActionType: '1'
    RemediationScanPreference: '0'
    BuildType: 'mvn'
    BuildCommand: 'clean verify -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
    PolicyFailAction: '1'

- bash: cp -a /home/vsts/.fortify/scancentral-23.2.1/log/. $(Agent.TempDirectory)/